apply plugin: 'com.android.library'

ext {
    publishVersion = rootProject.skinAndroidXVersion
    publishGroup = rootProject.skinAndroidXSkinGroup
    artifactFilePath  = "${project.buildDir}/outputs/aar/${project.name}-" +
            "${(publishVersion.endsWith('SNAPSHOT') || publishVersion.endsWith('snapshot'))?'debug':'release'}.aar"
    moduleName = 'skin-support-appcompat'
    descContent = 'skin-support 基础控件换肤支持包'
}

android {
    compileSdk rootProject.compileSdkVersion
    namespace "skin.support.appcompat"
    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            res.srcDirs = ['src/main/res', 'src/main/res-alertdialog']
        }
    }

    buildFeatures{
        buildConfig = true
    }
}

task generateSourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    var src =  'sources'
    archiveClassifier.convention(src)
    archiveClassifier.set(src)
}

afterEvaluate {
    logger.quiet("当前version:{}",publishVersion)
    def snapShortVer = publishVersion.endsWith('SNAPSHOT') || publishVersion.endsWith('snapshot')
    tasks.matching {
        (it.name.endsWith('artifactoryPublish') || it.name.endsWith('publishAarPublicationToMavenLocal'))
    }.each { tk ->
        tk.dependsOn("assemble${snapShortVer?'Debug':'Release'}", "generateSourcesJar")
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation "com.moorgen.sdk:common:1.7.9.1"
    implementation project(':androidx:skin-support')
}

tasks.withType(Javadoc) {
    options.addStringOption('Xdoclint:none', '-quiet')
    options.addStringOption('encoding', 'UTF-8')
    options.addStringOption('charSet', 'UTF-8')
}



//apply from: '../../publishing_maven.gradle'
apply from: '../../publishing_localmaven.gradle'