apply plugin: 'com.android.library'

ext {
    publishVersion = rootProject.skinAndroidXVersion
    publishGroup = rootProject.skinAndroidXSkinGroup
    artifactFilePath  = "${project.buildDir}/outputs/aar/${project.name}-" +
            "${(publishVersion.endsWith('SNAPSHOT') || publishVersion.endsWith('snapshot'))?'debug':'release'}.aar"
    moduleName = 'skin-support-constraint-layout'
    descContent = 'ConstraintLayout控件换肤支持包'
}

android {
    compileSdk rootProject.compileSdkVersion
    namespace "skin.support.constraint"

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures{
        buildConfig = true
    }
}

task generateSourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    var src =  'sources'
    archiveClassifier.convention(src)
    archiveClassifier.set(src)
}

afterEvaluate {
    logger.quiet("当前version:{}",publishVersion)
    def snapShortVer = publishVersion.endsWith('SNAPSHOT') || publishVersion.endsWith('snapshot')
    tasks.matching {
        (it.name.endsWith('artifactoryPublish') || it.name.endsWith('publishAarPublicationToMavenLocal'))
    }.each { tk ->
        tk.dependsOn("assemble${snapShortVer?'Debug':'Release'}", "generateSourcesJar")
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "com.moorgen.sdk:common:1.7.9.1"
    implementation project(':androidx:skin-support')
    implementation project(':androidx:skin-support-appcompat')
}



//apply from: '../../publishing_maven.gradle'
apply from: '../../publishing_localmaven.gradle'
