apply plugin: 'com.android.application'

android {
    compileSdk rootProject.compileSdkVersion
    namespace "com.ximsfei.skindemo"
    defaultConfig {
        applicationId "com.ximsfei.skindemo"
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            res.srcDirs = ['src/main/res', 'src/main/res-night']
        }
    }
    buildFeatures{
        buildConfig = true
    }
}

afterEvaluate {
    //开始配置项目之前删除皮肤包资源,以便于重新生成
    def skinFile =file(project.rootDir.absolutePath + "/demo/skin-androidx-app/src/main/assets/skins/night.skin")
    if(skinFile.exists()){
        if(skinFile.delete()){
            logger.quiet("存在的旧的的 skin package 已经被删除")
        }else{
            def errMsg =  "旧的的 skin package 删除失败"
            logger.log(LogLevel.ERROR,errMsg)
            assert false
        }
    }else{
        logger.log(LogLevel.WARN,"不存存在的旧的的 skin package")
    }

    tasks.matching {
        (it.name.endsWith('mergeDebugAssets')||it.name.endsWith('mergeReleaseAssets'))
    }.each { tk ->
        tk.dependsOn(':demo:skin-night:packageRelease')
    }

    tasks.matching {
        (it.name.endsWith('packageDebug')||it.name.endsWith('packageRelease'))
    }.each { tk ->
        tk.dependsOn(':demo:skin-night:packageRelease')
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation project(':androidx:skin-support')
//    implementation "android.skin:skin-support:${skinAndroidXVersion}"

    implementation project(':androidx:skin-support-appcompat')
//    implementation "android.skin:skin-support-appcompat:${skinAndroidXVersion}"

    implementation 'com.google.android.material:material:1.0.0'
    implementation project(':androidx:skin-support-design')
//    implementation "android.skin:skin-support-design:${skinAndroidXVersion}"

    implementation "androidx.constraintlayout:constraintlayout:2.1.4"
    implementation project(':androidx:skin-support-constraint-layout')
//    implementation "android.skin:skin-support-constraint-layout:${skinAndroidXVersion}"

    implementation 'androidx.cardview:cardview:1.0.0'
    implementation project(':androidx:skin-support-cardview')
//    implementation "android.skin:skin-support-cardview:${skinAndroidXVersion}"

    // 第三方控件库换肤支持
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation project(':third-part-support:circleimageview')
//    implementation "android.skin:circleimageview:${skinAndroidXVersion}"

     implementation 'io.github.h07000223:flycoTabLayout:3.0.0'
     implementation project(':third-part-support:flycotablayout')
//    implementation "android.skin:flycotablayout:${skinAndroidXVersion}"

    implementation "com.github.bumptech.glide:glide:${rootProject.glideVersion}"
    annotationProcessor "com.github.bumptech.glide:compiler:${rootProject.glideVersion}"
}
